---
title: "Opensource Driven Data Pipes"
subtitle: "How KOF uses R, PostgreSQL, Git and Co."
author: "Matthias Bannert"
date: "Jan 11, 2018"
output: ioslides_presentation
widescreen: true
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Background Poll

## About KOF

[=> KOF about KOF](https://www.kof.ethz.ch/en/)

## Requirements

- ensure documentation and long term knowledge transfer
- timely data imports
- reproducibly process data
- disseminate data
- publish KOF products
- enable language agnostic consumption


## Stack 

- git
- gitlab
- github
- R
- R Studio Server
- PostgreSQL
- PHP
- nginx
- shiny server
- dygraphs
- KONG
- Python
- RHEL


## Implementation - Robustness & Longevity

- de-centralized version control /w git
- host git repos on [gitlab](https://gitlab.ethz.ch) and [github](https://github.com/KOF-ch/)
- create packages to force documentation, e.g.,
    - kofdata ([CRAN](https://cran.r-project.org/web/packages/kofdata/index.html))
    - timeseriesdb ([github](https://github.com/mbannert/timeseriesdb))
    - tstools ([github](https://github.com/mbannert/tstools))
    - kofbts (internal)
    - kofbarometer (internal)
    - ... 
- mkdocs (markdown based documentation), mediawiki
- use a database, not filesystem based organization
- use servers to avoid maintenance issues in production

## Git - a micro excursion

- git is not a dropbox style sync
- git is decentralized 
- git is not github 
- git itself is a console program, GUIs come on top
- applied example: [*diff*erence between versions]()


## Overview


## Data imports

- use API whenever possible 
    - [SNB data](data.snb.ch)
    - [BFS PX web](https://www.pxweb.bfs.admin.ch/)
- time controlled R scripts (cronjobs) on servers
- assign unique keys following: 
country.provider.source.level.instance.variable.item
- store to postgreSQL database using R script


## Reproducibly Process Data

- scripts, mostly packages
- unit tests (introduction phase)
- no point and click processes
- log files
- error notifications mails
- GUI for production processes
- data.table, seasonal
- use tryCatch
- knitr / rmarkdown, tstools

## Disseminate Data: datenservice.kof.ethz.ch API

- REST API (compose URL dynamically)
  - ordinary links
  - use curl based, automated downloads
  - file based endpoints
  - dynamic endpoints
- kofdata R and Python packages (API wrapper)

## Publish Data

- KOF Website
- KOF Indicator Dashboard
- publish / subscribe (introduction phase)
- move timeseries data from one schema to another (updates all links and graphs)

[e.g. KOF Barometer](https://www.kof.ethz.ch/en/forecasts-and-indicators/indicators/kof-economic-barometer.html)


## Implementation Details: timeseriesdb

- map R time series objects to PostgreSQL table relations
- uses hstore key-value pair storage
- can store vintages


## KOF Reports


















